#!/bin/sh
#
# Script to rebase a Git submodule against origin and update the master project.

# Ensure "git" binary can be found (e.g. if running from cron)
PATH=$PATH:/usr/bin

# Module name is given as the first parameter
MODULE=$1

BASEDIR=`pwd`

# Rebase submodule against latest code in origin (e.g. GitHub)
echo -n "$MODULE: "
cd $MODULE
git pull --rebase origin

cd $BASEDIR

# Check if we need to update the submodule pointer. Later we might want to 
# consider a cleaner approach.
git status|grep "modified:.*$MODULE ("

if [ $? -eq 0 ]; then
    git add $MODULE
    git commit -m "Updated submodule pointer for $MODULE" -s $MODULE
fi
